# Generated by Django 3.1.2 on 2020-10-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('account_number', models.IntegerField()),
                ('routing_number', models.IntegerField()),
                ('account_hold_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('expiration', models.CharField(max_length=7)),
                ('security_code', models.IntegerField()),
                ('billing_address', models.CharField(max_length=50)),
                ('card_holder_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_of_credential', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('bankdrafts', models.ManyToManyField(blank=True, null=True, to='webauto.BankDraft')),
                ('creditcards', models.ManyToManyField(blank=True, null=True, to='webauto.CreditCard')),
            ],
        ),
    ]
