# Generated by Django 3.1.2 on 2020-10-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdraft',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankdraft',
            name='routing_number',
            field=models.CharField(max_length=20),
        ),
    ]
