# Generated by Django 3.1.2 on 2020-11-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauto', '0002_auto_20201030_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdraft',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdraft',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
